name: Latest blog posts
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-latest-blog-posts:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://sametcelikbicak.com/rss.xml"
